package com.sloimay.smath.numexts

import kotlin.math.floor
import kotlin.math.round
import kotlin.math.ceil
import kotlin.math.min
import kotlin.math.max
import kotlin.math.abs

import kotlin.math.sin
import kotlin.math.cos
import kotlin.math.tan
import kotlin.math.asin
import kotlin.math.acos
import kotlin.math.atan
import kotlin.math.sinh
import kotlin.math.cosh
import kotlin.math.tanh
import kotlin.math.asinh
import kotlin.math.acosh
import kotlin.math.atanh

import kotlin.math.sqrt
import kotlin.math.cbrt
import kotlin.math.ln
import kotlin.math.ln1p
import kotlin.math.log10
import kotlin.math.log2
import kotlin.math.exp
import kotlin.math.expm1

fun Byte.abs() = abs(this.toInt()).toByte()
fun Byte.sin() = sin(this.toFloat())
fun Byte.cos() = cos(this.toFloat())
fun Byte.tan() = tan(this.toFloat())
fun Byte.asin() = asin(this.toFloat())
fun Byte.acos() = acos(this.toFloat())
fun Byte.atan() = atan(this.toFloat())
fun Byte.sinh() = sinh(this.toFloat())
fun Byte.cosh() = cosh(this.toFloat())
fun Byte.tanh() = tanh(this.toFloat())
fun Byte.asinh() = asinh(this.toFloat())
fun Byte.acosh() = acosh(this.toFloat())
fun Byte.atanh() = atanh(this.toFloat())
fun Byte.sqrt() = sqrt(this.toFloat())
fun Byte.cbrt() = cbrt(this.toFloat())
fun Byte.ln() = ln(this.toFloat())
fun Byte.ln1p() = ln1p(this.toFloat())
fun Byte.log2() = log2(this.toFloat())
fun Byte.log10() = log10(this.toFloat())
fun Byte.exp() = exp(this.toFloat())
fun Byte.expm1() = expm1(this.toFloat())

fun UByte.sin() = sin(this.toFloat())
fun UByte.cos() = cos(this.toFloat())
fun UByte.tan() = tan(this.toFloat())
fun UByte.asin() = asin(this.toFloat())
fun UByte.acos() = acos(this.toFloat())
fun UByte.atan() = atan(this.toFloat())
fun UByte.sinh() = sinh(this.toFloat())
fun UByte.cosh() = cosh(this.toFloat())
fun UByte.tanh() = tanh(this.toFloat())
fun UByte.asinh() = asinh(this.toFloat())
fun UByte.acosh() = acosh(this.toFloat())
fun UByte.atanh() = atanh(this.toFloat())
fun UByte.sqrt() = sqrt(this.toFloat())
fun UByte.cbrt() = cbrt(this.toFloat())
fun UByte.ln() = ln(this.toFloat())
fun UByte.ln1p() = ln1p(this.toFloat())
fun UByte.log2() = log2(this.toFloat())
fun UByte.log10() = log10(this.toFloat())
fun UByte.exp() = exp(this.toFloat())
fun UByte.expm1() = expm1(this.toFloat())

fun Short.abs() = abs(this.toInt()).toShort()
fun Short.sin() = sin(this.toFloat())
fun Short.cos() = cos(this.toFloat())
fun Short.tan() = tan(this.toFloat())
fun Short.asin() = asin(this.toFloat())
fun Short.acos() = acos(this.toFloat())
fun Short.atan() = atan(this.toFloat())
fun Short.sinh() = sinh(this.toFloat())
fun Short.cosh() = cosh(this.toFloat())
fun Short.tanh() = tanh(this.toFloat())
fun Short.asinh() = asinh(this.toFloat())
fun Short.acosh() = acosh(this.toFloat())
fun Short.atanh() = atanh(this.toFloat())
fun Short.sqrt() = sqrt(this.toFloat())
fun Short.cbrt() = cbrt(this.toFloat())
fun Short.ln() = ln(this.toFloat())
fun Short.ln1p() = ln1p(this.toFloat())
fun Short.log2() = log2(this.toFloat())
fun Short.log10() = log10(this.toFloat())
fun Short.exp() = exp(this.toFloat())
fun Short.expm1() = expm1(this.toFloat())

fun UShort.sin() = sin(this.toFloat())
fun UShort.cos() = cos(this.toFloat())
fun UShort.tan() = tan(this.toFloat())
fun UShort.asin() = asin(this.toFloat())
fun UShort.acos() = acos(this.toFloat())
fun UShort.atan() = atan(this.toFloat())
fun UShort.sinh() = sinh(this.toFloat())
fun UShort.cosh() = cosh(this.toFloat())
fun UShort.tanh() = tanh(this.toFloat())
fun UShort.asinh() = asinh(this.toFloat())
fun UShort.acosh() = acosh(this.toFloat())
fun UShort.atanh() = atanh(this.toFloat())
fun UShort.sqrt() = sqrt(this.toFloat())
fun UShort.cbrt() = cbrt(this.toFloat())
fun UShort.ln() = ln(this.toFloat())
fun UShort.ln1p() = ln1p(this.toFloat())
fun UShort.log2() = log2(this.toFloat())
fun UShort.log10() = log10(this.toFloat())
fun UShort.exp() = exp(this.toFloat())
fun UShort.expm1() = expm1(this.toFloat())

fun Int.abs() = abs(this)
fun Int.sin() = sin(this.toDouble())
fun Int.cos() = cos(this.toDouble())
fun Int.tan() = tan(this.toDouble())
fun Int.asin() = asin(this.toDouble())
fun Int.acos() = acos(this.toDouble())
fun Int.atan() = atan(this.toDouble())
fun Int.sinh() = sinh(this.toDouble())
fun Int.cosh() = cosh(this.toDouble())
fun Int.tanh() = tanh(this.toDouble())
fun Int.asinh() = asinh(this.toDouble())
fun Int.acosh() = acosh(this.toDouble())
fun Int.atanh() = atanh(this.toDouble())
fun Int.sqrt() = sqrt(this.toDouble())
fun Int.cbrt() = cbrt(this.toDouble())
fun Int.ln() = ln(this.toDouble())
fun Int.ln1p() = ln1p(this.toDouble())
fun Int.log2() = log2(this.toDouble())
fun Int.log10() = log10(this.toDouble())
fun Int.exp() = exp(this.toDouble())
fun Int.expm1() = expm1(this.toDouble())

fun UInt.sin() = sin(this.toDouble())
fun UInt.cos() = cos(this.toDouble())
fun UInt.tan() = tan(this.toDouble())
fun UInt.asin() = asin(this.toDouble())
fun UInt.acos() = acos(this.toDouble())
fun UInt.atan() = atan(this.toDouble())
fun UInt.sinh() = sinh(this.toDouble())
fun UInt.cosh() = cosh(this.toDouble())
fun UInt.tanh() = tanh(this.toDouble())
fun UInt.asinh() = asinh(this.toDouble())
fun UInt.acosh() = acosh(this.toDouble())
fun UInt.atanh() = atanh(this.toDouble())
fun UInt.sqrt() = sqrt(this.toDouble())
fun UInt.cbrt() = cbrt(this.toDouble())
fun UInt.ln() = ln(this.toDouble())
fun UInt.ln1p() = ln1p(this.toDouble())
fun UInt.log2() = log2(this.toDouble())
fun UInt.log10() = log10(this.toDouble())
fun UInt.exp() = exp(this.toDouble())
fun UInt.expm1() = expm1(this.toDouble())

fun Long.abs() = abs(this)
fun Long.sin() = sin(this.toDouble())
fun Long.cos() = cos(this.toDouble())
fun Long.tan() = tan(this.toDouble())
fun Long.asin() = asin(this.toDouble())
fun Long.acos() = acos(this.toDouble())
fun Long.atan() = atan(this.toDouble())
fun Long.sinh() = sinh(this.toDouble())
fun Long.cosh() = cosh(this.toDouble())
fun Long.tanh() = tanh(this.toDouble())
fun Long.asinh() = asinh(this.toDouble())
fun Long.acosh() = acosh(this.toDouble())
fun Long.atanh() = atanh(this.toDouble())
fun Long.sqrt() = sqrt(this.toDouble())
fun Long.cbrt() = cbrt(this.toDouble())
fun Long.ln() = ln(this.toDouble())
fun Long.ln1p() = ln1p(this.toDouble())
fun Long.log2() = log2(this.toDouble())
fun Long.log10() = log10(this.toDouble())
fun Long.exp() = exp(this.toDouble())
fun Long.expm1() = expm1(this.toDouble())

fun ULong.sin() = sin(this.toDouble())
fun ULong.cos() = cos(this.toDouble())
fun ULong.tan() = tan(this.toDouble())
fun ULong.asin() = asin(this.toDouble())
fun ULong.acos() = acos(this.toDouble())
fun ULong.atan() = atan(this.toDouble())
fun ULong.sinh() = sinh(this.toDouble())
fun ULong.cosh() = cosh(this.toDouble())
fun ULong.tanh() = tanh(this.toDouble())
fun ULong.asinh() = asinh(this.toDouble())
fun ULong.acosh() = acosh(this.toDouble())
fun ULong.atanh() = atanh(this.toDouble())
fun ULong.sqrt() = sqrt(this.toDouble())
fun ULong.cbrt() = cbrt(this.toDouble())
fun ULong.ln() = ln(this.toDouble())
fun ULong.ln1p() = ln1p(this.toDouble())
fun ULong.log2() = log2(this.toDouble())
fun ULong.log10() = log10(this.toDouble())
fun ULong.exp() = exp(this.toDouble())
fun ULong.expm1() = expm1(this.toDouble())

fun Float.min(other: Float) = min(this, other)
fun Float.max(other: Float) = max(this, other)
fun Float.floor() = floor(this)
fun Float.ceil() = ceil(this)
fun Float.round() = round(this)
fun Float.clamp(low: Float, high: Float) = max(min(this, high), low)
fun Float.lerp(other: Float, t: Float) = this*(1f-t) + other*t
fun Float.abs() = abs(this)
fun Float.sin() = sin(this.toDouble())
fun Float.cos() = cos(this.toDouble())
fun Float.tan() = tan(this.toDouble())
fun Float.asin() = asin(this.toDouble())
fun Float.acos() = acos(this.toDouble())
fun Float.atan() = atan(this.toDouble())
fun Float.sinh() = sinh(this.toDouble())
fun Float.cosh() = cosh(this.toDouble())
fun Float.tanh() = tanh(this.toDouble())
fun Float.asinh() = asinh(this.toDouble())
fun Float.acosh() = acosh(this.toDouble())
fun Float.atanh() = atanh(this.toDouble())
fun Float.sqrt() = sqrt(this.toDouble())
fun Float.cbrt() = cbrt(this.toDouble())
fun Float.ln() = ln(this.toDouble())
fun Float.ln1p() = ln1p(this.toDouble())
fun Float.log2() = log2(this.toDouble())
fun Float.log10() = log10(this.toDouble())
fun Float.exp() = exp(this.toDouble())
fun Float.expm1() = expm1(this.toDouble())

fun Double.min(other: Double) = min(this, other)
fun Double.max(other: Double) = max(this, other)
fun Double.floor() = floor(this)
fun Double.ceil() = ceil(this)
fun Double.round() = round(this)
fun Double.clamp(low: Double, high: Double) = max(min(this, high), low)
fun Double.lerp(other: Double, t: Double) = this*(1f-t) + other*t
fun Double.abs() = abs(this)
fun Double.sin() = sin(this)
fun Double.cos() = cos(this)
fun Double.tan() = tan(this)
fun Double.asin() = asin(this)
fun Double.acos() = acos(this)
fun Double.atan() = atan(this)
fun Double.sinh() = sinh(this)
fun Double.cosh() = cosh(this)
fun Double.tanh() = tanh(this)
fun Double.asinh() = asinh(this)
fun Double.acosh() = acosh(this)
fun Double.atanh() = atanh(this)
fun Double.sqrt() = sqrt(this)
fun Double.cbrt() = cbrt(this)
fun Double.ln() = ln(this)
fun Double.ln1p() = ln1p(this)
fun Double.log2() = log2(this)
fun Double.log10() = log10(this)
fun Double.exp() = exp(this)
fun Double.expm1() = expm1(this)
