package com.sloimay.smath.vectors

import java.util.*
import kotlin.math.*

data class DVec4(val x: Double, val y: Double, val z: Double, val w: Double) {

    companion object {
        fun splat(value: Byte) = DVec4(value, value, value, value)
        fun splat(value: Short) = DVec4(value, value, value, value)
        fun splat(value: Int) = DVec4(value, value, value, value)
        fun splat(value: Long) = DVec4(value, value, value, value)
        fun splat(value: Float) = DVec4(value, value, value, value)
        fun splat(value: Double) = DVec4(value, value, value, value)
        fun new(x: Byte, y: Byte, z: Byte, w: Byte) = DVec4(x, y, z, w)
        fun new(x: Short, y: Short, z: Short, w: Short) = DVec4(x, y, z, w)
        fun new(x: Int, y: Int, z: Int, w: Int) = DVec4(x, y, z, w)
        fun new(x: Long, y: Long, z: Long, w: Long) = DVec4(x, y, z, w)
        fun new(x: Float, y: Float, z: Float, w: Float) = DVec4(x, y, z, w)
        fun new(x: Double, y: Double, z: Double, w: Double) = DVec4(x, y, z, w)

        fun fromArray(array: DoubleArray): DVec4 {
            require(array.size == 4) { 
                "Inputted array isn't of the same dimensions as the vector we're trying to create. Expected 4, got ${array.size}."
            }
            return DVec4(array[0], array[1], array[2], array[3])
        }

        val X: DVec4 = DVec4(1.0, 0.0, 0.0, 0.0)
        val Y: DVec4 = DVec4(0.0, 1.0, 0.0, 0.0)
        val Z: DVec4 = DVec4(0.0, 0.0, 1.0, 0.0)
        val W: DVec4 = DVec4(0.0, 0.0, 0.0, 1.0)
        val ZERO: DVec4 = DVec4(0.0)
        val ONE: DVec4 = DVec4(1.0)
        val INF: DVec4 = DVec4(Double.POSITIVE_INFINITY)
        val NEG_INF: DVec4 = DVec4(Double.NEGATIVE_INFINITY)
        val MIN: DVec4 = DVec4(Double.MIN_VALUE)
        val MAX: DVec4 = DVec4(Double.MAX_VALUE)
    }

    constructor(value: Byte) : this(value.toDouble(), value.toDouble(), value.toDouble(), value.toDouble())
    constructor(x: Byte, y: Byte, z: Byte, w: Byte) : this(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
    constructor(value: Short) : this(value.toDouble(), value.toDouble(), value.toDouble(), value.toDouble())
    constructor(x: Short, y: Short, z: Short, w: Short) : this(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
    constructor(value: Int) : this(value.toDouble(), value.toDouble(), value.toDouble(), value.toDouble())
    constructor(x: Int, y: Int, z: Int, w: Int) : this(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
    constructor(value: Long) : this(value.toDouble(), value.toDouble(), value.toDouble(), value.toDouble())
    constructor(x: Long, y: Long, z: Long, w: Long) : this(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
    constructor(value: Float) : this(value.toDouble(), value.toDouble(), value.toDouble(), value.toDouble())
    constructor(x: Float, y: Float, z: Float, w: Float) : this(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
    constructor(value: Double) : this(value, value, value, value)
    constructor() : this(0.0, 0.0, 0.0, 0.0)
    constructor(lamb: (Int) -> Double) : this(lamb(0), lamb(1), lamb(2), lamb(3))

    operator fun plus(other: DVec4) = DVec4(x + other.x, y + other.y, z + other.z, w + other.w)
    operator fun plus(other: Double) = DVec4(x + other, y + other, z + other, w + other)
    operator fun minus(other: DVec4) = DVec4(x - other.x, y - other.y, z - other.z, w - other.w)
    operator fun minus(other: Double) = DVec4(x - other, y - other, z - other, w - other)
    operator fun times(other: DVec4) = DVec4(x * other.x, y * other.y, z * other.z, w * other.w)
    operator fun times(other: Double) = DVec4(x * other, y * other, z * other, w * other)
    operator fun div(other: DVec4) = DVec4(x / other.x, y / other.y, z / other.z, w / other.w)
    operator fun div(other: Double) = DVec4(x / other, y / other, z / other, w / other)
    operator fun rem(other: DVec4) = DVec4(x % other.x, y % other.y, z % other.z, w % other.w)
    operator fun rem(other: Double) = DVec4(x % other, y % other, z % other, w % other)
    operator fun unaryPlus() = this
    operator fun unaryMinus() = DVec4(-x, -y, -z, -w)
    operator fun get(idx: Byte): Double {
        require(idx in 0 until 4) { 
            "DVec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx.toInt()) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }
    operator fun get(idx: Short): Double {
        require(idx in 0 until 4) { 
            "DVec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx.toInt()) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }
    operator fun get(idx: Int): Double {
        require(idx in 0 until 4) { 
            "DVec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }
    operator fun get(idx: Long): Double {
        require(idx in 0 until 4) { 
            "DVec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx.toInt()) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }

    fun toBVec4() = BVec4(x.toInt().toByte(), y.toInt().toByte(), z.toInt().toByte(), w.toInt().toByte())
    fun toSVec4() = SVec4(x.toInt().toShort(), y.toInt().toShort(), z.toInt().toShort(), w.toInt().toShort())
    fun toIVec4() = IVec4(x.toInt(), y.toInt(), z.toInt(), w.toInt())
    fun toLVec4() = LVec4(x.toLong(), y.toLong(), z.toLong(), w.toLong())
    fun toVec4() = Vec4(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())

    fun eq(other: DVec4) = x == other.x && y == other.y && z == other.z && w == other.w
    fun abs() = DVec4(abs(x), abs(y), abs(z), abs(w))
    fun mod(value: Double) = DVec4(x.mod(value), y.mod(value), z.mod(value), w.mod(value))
    fun mod(other: DVec4) = DVec4(x.mod(other.x), y.mod(other.y), z.mod(other.z), w.mod(other.w))
    fun min(other: DVec4) = DVec4(min(x, other.x), min(y, other.y), min(z, other.z), min(w, other.w))
    fun max(other: DVec4) = DVec4(max(x, other.x), max(y, other.y), max(z, other.z), max(w, other.w))
    fun clamp(low: DVec4, high: DVec4) = DVec4(max(min(x, high.x), low.x), max(min(y, high.y), low.y), max(min(z, high.z), low.z), max(min(w, high.w), low.w))
    fun dot(other: DVec4) = x * other.x + y * other.y + z * other.z + w * other.w
    fun lenSq() = dot(this)
    fun len() = sqrt(lenSq())
    fun dist(other: DVec4) = (this - other).len()
    fun distSq(other: DVec4) = (this - other).lenSq()
    fun normalize() = this / len()
    fun dir() = this / len()
    fun elementSum() = x + y + z + w
    fun eSum() = x + y + z + w
    fun elementProd() = x * y * z * w
    fun eProd() = x * y * z * w
    fun minElement() = min(min(x, y), min(z, w))
    fun eMin() = min(min(x, y), min(z, w))
    fun maxElement() = max(max(x, y), max(z, w))
    fun eMax() = max(max(x, y), max(z, w))
    fun indexOfMin() = when (eMin()) { x -> 0; y -> 1; z -> 2; else -> 3 }
    fun indexOfMax() = when (eMax()) { x -> 0; y -> 1; z -> 2; else -> 3 }
    fun manhattan(other: DVec4) = (this - other).abs().eSum()
    fun toArray() = doubleArrayOf(x, y, z, w)
    fun lerp(other: DVec4, t: Double) = this * (1.0 - t) + other * t
    fun floor() = DVec4(floor(x), floor(y), floor(z), floor(w))
    fun ceil() = DVec4(ceil(x), ceil(y), ceil(z), ceil(w))
    fun round() = DVec4(round(x), round(y), round(z), round(w))
    fun fract() = mod(1.0)

    fun withElement(elementIdx: Int, value: Byte) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Short) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Int) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Long) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Float) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Double) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun perm(other: BVec2) = DVec2(this[other.x.toInt()], this[other.y.toInt()])
    fun perm(other: SVec2) = DVec2(this[other.x.toInt()], this[other.y.toInt()])
    fun perm(other: IVec2) = DVec2(this[other.x], this[other.y])
    fun perm(other: LVec2) = DVec2(this[other.x.toInt()], this[other.y.toInt()])
    fun perm(other: BVec3) = DVec3(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()])
    fun perm(other: SVec3) = DVec3(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()])
    fun perm(other: IVec3) = DVec3(this[other.x], this[other.y], this[other.z])
    fun perm(other: LVec3) = DVec3(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()])
    fun perm(other: BVec4) = DVec4(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()], this[other.w.toInt()])
    fun perm(other: SVec4) = DVec4(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()], this[other.w.toInt()])
    fun perm(other: IVec4) = DVec4(this[other.x], this[other.y], this[other.z], this[other.w])
    fun perm(other: LVec4) = DVec4(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()], this[other.w.toInt()])
    fun withX(value: Byte) = DVec4(value.toDouble(), y, z, w)
    fun withX(value: Short) = DVec4(value.toDouble(), y, z, w)
    fun withX(value: Int) = DVec4(value.toDouble(), y, z, w)
    fun withX(value: Long) = DVec4(value.toDouble(), y, z, w)
    fun withX(value: Float) = DVec4(value.toDouble(), y, z, w)
    fun withX(value: Double) = DVec4(value, y, z, w)
    fun withY(value: Byte) = DVec4(x, value.toDouble(), z, w)
    fun withY(value: Short) = DVec4(x, value.toDouble(), z, w)
    fun withY(value: Int) = DVec4(x, value.toDouble(), z, w)
    fun withY(value: Long) = DVec4(x, value.toDouble(), z, w)
    fun withY(value: Float) = DVec4(x, value.toDouble(), z, w)
    fun withY(value: Double) = DVec4(x, value, z, w)
    fun withZ(value: Byte) = DVec4(x, y, value.toDouble(), w)
    fun withZ(value: Short) = DVec4(x, y, value.toDouble(), w)
    fun withZ(value: Int) = DVec4(x, y, value.toDouble(), w)
    fun withZ(value: Long) = DVec4(x, y, value.toDouble(), w)
    fun withZ(value: Float) = DVec4(x, y, value.toDouble(), w)
    fun withZ(value: Double) = DVec4(x, y, value, w)
    fun withW(value: Byte) = DVec4(x, y, z, value.toDouble())
    fun withW(value: Short) = DVec4(x, y, z, value.toDouble())
    fun withW(value: Int) = DVec4(x, y, z, value.toDouble())
    fun withW(value: Long) = DVec4(x, y, z, value.toDouble())
    fun withW(value: Float) = DVec4(x, y, z, value.toDouble())
    fun withW(value: Double) = DVec4(x, y, z, value)

    val xx get() = DVec2(x, x)
    val xy get() = DVec2(x, y)
    val xz get() = DVec2(x, z)
    val xw get() = DVec2(x, w)
    val yx get() = DVec2(y, x)
    val yy get() = DVec2(y, y)
    val yz get() = DVec2(y, z)
    val yw get() = DVec2(y, w)
    val zx get() = DVec2(z, x)
    val zy get() = DVec2(z, y)
    val zz get() = DVec2(z, z)
    val zw get() = DVec2(z, w)
    val wx get() = DVec2(w, x)
    val wy get() = DVec2(w, y)
    val wz get() = DVec2(w, z)
    val ww get() = DVec2(w, w)
    val xxx get() = DVec3(x, x, x)
    val xxy get() = DVec3(x, x, y)
    val xxz get() = DVec3(x, x, z)
    val xxw get() = DVec3(x, x, w)
    val xyx get() = DVec3(x, y, x)
    val xyy get() = DVec3(x, y, y)
    val xyz get() = DVec3(x, y, z)
    val xyw get() = DVec3(x, y, w)
    val xzx get() = DVec3(x, z, x)
    val xzy get() = DVec3(x, z, y)
    val xzz get() = DVec3(x, z, z)
    val xzw get() = DVec3(x, z, w)
    val xwx get() = DVec3(x, w, x)
    val xwy get() = DVec3(x, w, y)
    val xwz get() = DVec3(x, w, z)
    val xww get() = DVec3(x, w, w)
    val yxx get() = DVec3(y, x, x)
    val yxy get() = DVec3(y, x, y)
    val yxz get() = DVec3(y, x, z)
    val yxw get() = DVec3(y, x, w)
    val yyx get() = DVec3(y, y, x)
    val yyy get() = DVec3(y, y, y)
    val yyz get() = DVec3(y, y, z)
    val yyw get() = DVec3(y, y, w)
    val yzx get() = DVec3(y, z, x)
    val yzy get() = DVec3(y, z, y)
    val yzz get() = DVec3(y, z, z)
    val yzw get() = DVec3(y, z, w)
    val ywx get() = DVec3(y, w, x)
    val ywy get() = DVec3(y, w, y)
    val ywz get() = DVec3(y, w, z)
    val yww get() = DVec3(y, w, w)
    val zxx get() = DVec3(z, x, x)
    val zxy get() = DVec3(z, x, y)
    val zxz get() = DVec3(z, x, z)
    val zxw get() = DVec3(z, x, w)
    val zyx get() = DVec3(z, y, x)
    val zyy get() = DVec3(z, y, y)
    val zyz get() = DVec3(z, y, z)
    val zyw get() = DVec3(z, y, w)
    val zzx get() = DVec3(z, z, x)
    val zzy get() = DVec3(z, z, y)
    val zzz get() = DVec3(z, z, z)
    val zzw get() = DVec3(z, z, w)
    val zwx get() = DVec3(z, w, x)
    val zwy get() = DVec3(z, w, y)
    val zwz get() = DVec3(z, w, z)
    val zww get() = DVec3(z, w, w)
    val wxx get() = DVec3(w, x, x)
    val wxy get() = DVec3(w, x, y)
    val wxz get() = DVec3(w, x, z)
    val wxw get() = DVec3(w, x, w)
    val wyx get() = DVec3(w, y, x)
    val wyy get() = DVec3(w, y, y)
    val wyz get() = DVec3(w, y, z)
    val wyw get() = DVec3(w, y, w)
    val wzx get() = DVec3(w, z, x)
    val wzy get() = DVec3(w, z, y)
    val wzz get() = DVec3(w, z, z)
    val wzw get() = DVec3(w, z, w)
    val wwx get() = DVec3(w, w, x)
    val wwy get() = DVec3(w, w, y)
    val wwz get() = DVec3(w, w, z)
    val www get() = DVec3(w, w, w)
    val xxxx get() = DVec4(x, x, x, x)
    val xxxy get() = DVec4(x, x, x, y)
    val xxxz get() = DVec4(x, x, x, z)
    val xxxw get() = DVec4(x, x, x, w)
    val xxyx get() = DVec4(x, x, y, x)
    val xxyy get() = DVec4(x, x, y, y)
    val xxyz get() = DVec4(x, x, y, z)
    val xxyw get() = DVec4(x, x, y, w)
    val xxzx get() = DVec4(x, x, z, x)
    val xxzy get() = DVec4(x, x, z, y)
    val xxzz get() = DVec4(x, x, z, z)
    val xxzw get() = DVec4(x, x, z, w)
    val xxwx get() = DVec4(x, x, w, x)
    val xxwy get() = DVec4(x, x, w, y)
    val xxwz get() = DVec4(x, x, w, z)
    val xxww get() = DVec4(x, x, w, w)
    val xyxx get() = DVec4(x, y, x, x)
    val xyxy get() = DVec4(x, y, x, y)
    val xyxz get() = DVec4(x, y, x, z)
    val xyxw get() = DVec4(x, y, x, w)
    val xyyx get() = DVec4(x, y, y, x)
    val xyyy get() = DVec4(x, y, y, y)
    val xyyz get() = DVec4(x, y, y, z)
    val xyyw get() = DVec4(x, y, y, w)
    val xyzx get() = DVec4(x, y, z, x)
    val xyzy get() = DVec4(x, y, z, y)
    val xyzz get() = DVec4(x, y, z, z)
    val xyzw get() = DVec4(x, y, z, w)
    val xywx get() = DVec4(x, y, w, x)
    val xywy get() = DVec4(x, y, w, y)
    val xywz get() = DVec4(x, y, w, z)
    val xyww get() = DVec4(x, y, w, w)
    val xzxx get() = DVec4(x, z, x, x)
    val xzxy get() = DVec4(x, z, x, y)
    val xzxz get() = DVec4(x, z, x, z)
    val xzxw get() = DVec4(x, z, x, w)
    val xzyx get() = DVec4(x, z, y, x)
    val xzyy get() = DVec4(x, z, y, y)
    val xzyz get() = DVec4(x, z, y, z)
    val xzyw get() = DVec4(x, z, y, w)
    val xzzx get() = DVec4(x, z, z, x)
    val xzzy get() = DVec4(x, z, z, y)
    val xzzz get() = DVec4(x, z, z, z)
    val xzzw get() = DVec4(x, z, z, w)
    val xzwx get() = DVec4(x, z, w, x)
    val xzwy get() = DVec4(x, z, w, y)
    val xzwz get() = DVec4(x, z, w, z)
    val xzww get() = DVec4(x, z, w, w)
    val xwxx get() = DVec4(x, w, x, x)
    val xwxy get() = DVec4(x, w, x, y)
    val xwxz get() = DVec4(x, w, x, z)
    val xwxw get() = DVec4(x, w, x, w)
    val xwyx get() = DVec4(x, w, y, x)
    val xwyy get() = DVec4(x, w, y, y)
    val xwyz get() = DVec4(x, w, y, z)
    val xwyw get() = DVec4(x, w, y, w)
    val xwzx get() = DVec4(x, w, z, x)
    val xwzy get() = DVec4(x, w, z, y)
    val xwzz get() = DVec4(x, w, z, z)
    val xwzw get() = DVec4(x, w, z, w)
    val xwwx get() = DVec4(x, w, w, x)
    val xwwy get() = DVec4(x, w, w, y)
    val xwwz get() = DVec4(x, w, w, z)
    val xwww get() = DVec4(x, w, w, w)
    val yxxx get() = DVec4(y, x, x, x)
    val yxxy get() = DVec4(y, x, x, y)
    val yxxz get() = DVec4(y, x, x, z)
    val yxxw get() = DVec4(y, x, x, w)
    val yxyx get() = DVec4(y, x, y, x)
    val yxyy get() = DVec4(y, x, y, y)
    val yxyz get() = DVec4(y, x, y, z)
    val yxyw get() = DVec4(y, x, y, w)
    val yxzx get() = DVec4(y, x, z, x)
    val yxzy get() = DVec4(y, x, z, y)
    val yxzz get() = DVec4(y, x, z, z)
    val yxzw get() = DVec4(y, x, z, w)
    val yxwx get() = DVec4(y, x, w, x)
    val yxwy get() = DVec4(y, x, w, y)
    val yxwz get() = DVec4(y, x, w, z)
    val yxww get() = DVec4(y, x, w, w)
    val yyxx get() = DVec4(y, y, x, x)
    val yyxy get() = DVec4(y, y, x, y)
    val yyxz get() = DVec4(y, y, x, z)
    val yyxw get() = DVec4(y, y, x, w)
    val yyyx get() = DVec4(y, y, y, x)
    val yyyy get() = DVec4(y, y, y, y)
    val yyyz get() = DVec4(y, y, y, z)
    val yyyw get() = DVec4(y, y, y, w)
    val yyzx get() = DVec4(y, y, z, x)
    val yyzy get() = DVec4(y, y, z, y)
    val yyzz get() = DVec4(y, y, z, z)
    val yyzw get() = DVec4(y, y, z, w)
    val yywx get() = DVec4(y, y, w, x)
    val yywy get() = DVec4(y, y, w, y)
    val yywz get() = DVec4(y, y, w, z)
    val yyww get() = DVec4(y, y, w, w)
    val yzxx get() = DVec4(y, z, x, x)
    val yzxy get() = DVec4(y, z, x, y)
    val yzxz get() = DVec4(y, z, x, z)
    val yzxw get() = DVec4(y, z, x, w)
    val yzyx get() = DVec4(y, z, y, x)
    val yzyy get() = DVec4(y, z, y, y)
    val yzyz get() = DVec4(y, z, y, z)
    val yzyw get() = DVec4(y, z, y, w)
    val yzzx get() = DVec4(y, z, z, x)
    val yzzy get() = DVec4(y, z, z, y)
    val yzzz get() = DVec4(y, z, z, z)
    val yzzw get() = DVec4(y, z, z, w)
    val yzwx get() = DVec4(y, z, w, x)
    val yzwy get() = DVec4(y, z, w, y)
    val yzwz get() = DVec4(y, z, w, z)
    val yzww get() = DVec4(y, z, w, w)
    val ywxx get() = DVec4(y, w, x, x)
    val ywxy get() = DVec4(y, w, x, y)
    val ywxz get() = DVec4(y, w, x, z)
    val ywxw get() = DVec4(y, w, x, w)
    val ywyx get() = DVec4(y, w, y, x)
    val ywyy get() = DVec4(y, w, y, y)
    val ywyz get() = DVec4(y, w, y, z)
    val ywyw get() = DVec4(y, w, y, w)
    val ywzx get() = DVec4(y, w, z, x)
    val ywzy get() = DVec4(y, w, z, y)
    val ywzz get() = DVec4(y, w, z, z)
    val ywzw get() = DVec4(y, w, z, w)
    val ywwx get() = DVec4(y, w, w, x)
    val ywwy get() = DVec4(y, w, w, y)
    val ywwz get() = DVec4(y, w, w, z)
    val ywww get() = DVec4(y, w, w, w)
    val zxxx get() = DVec4(z, x, x, x)
    val zxxy get() = DVec4(z, x, x, y)
    val zxxz get() = DVec4(z, x, x, z)
    val zxxw get() = DVec4(z, x, x, w)
    val zxyx get() = DVec4(z, x, y, x)
    val zxyy get() = DVec4(z, x, y, y)
    val zxyz get() = DVec4(z, x, y, z)
    val zxyw get() = DVec4(z, x, y, w)
    val zxzx get() = DVec4(z, x, z, x)
    val zxzy get() = DVec4(z, x, z, y)
    val zxzz get() = DVec4(z, x, z, z)
    val zxzw get() = DVec4(z, x, z, w)
    val zxwx get() = DVec4(z, x, w, x)
    val zxwy get() = DVec4(z, x, w, y)
    val zxwz get() = DVec4(z, x, w, z)
    val zxww get() = DVec4(z, x, w, w)
    val zyxx get() = DVec4(z, y, x, x)
    val zyxy get() = DVec4(z, y, x, y)
    val zyxz get() = DVec4(z, y, x, z)
    val zyxw get() = DVec4(z, y, x, w)
    val zyyx get() = DVec4(z, y, y, x)
    val zyyy get() = DVec4(z, y, y, y)
    val zyyz get() = DVec4(z, y, y, z)
    val zyyw get() = DVec4(z, y, y, w)
    val zyzx get() = DVec4(z, y, z, x)
    val zyzy get() = DVec4(z, y, z, y)
    val zyzz get() = DVec4(z, y, z, z)
    val zyzw get() = DVec4(z, y, z, w)
    val zywx get() = DVec4(z, y, w, x)
    val zywy get() = DVec4(z, y, w, y)
    val zywz get() = DVec4(z, y, w, z)
    val zyww get() = DVec4(z, y, w, w)
    val zzxx get() = DVec4(z, z, x, x)
    val zzxy get() = DVec4(z, z, x, y)
    val zzxz get() = DVec4(z, z, x, z)
    val zzxw get() = DVec4(z, z, x, w)
    val zzyx get() = DVec4(z, z, y, x)
    val zzyy get() = DVec4(z, z, y, y)
    val zzyz get() = DVec4(z, z, y, z)
    val zzyw get() = DVec4(z, z, y, w)
    val zzzx get() = DVec4(z, z, z, x)
    val zzzy get() = DVec4(z, z, z, y)
    val zzzz get() = DVec4(z, z, z, z)
    val zzzw get() = DVec4(z, z, z, w)
    val zzwx get() = DVec4(z, z, w, x)
    val zzwy get() = DVec4(z, z, w, y)
    val zzwz get() = DVec4(z, z, w, z)
    val zzww get() = DVec4(z, z, w, w)
    val zwxx get() = DVec4(z, w, x, x)
    val zwxy get() = DVec4(z, w, x, y)
    val zwxz get() = DVec4(z, w, x, z)
    val zwxw get() = DVec4(z, w, x, w)
    val zwyx get() = DVec4(z, w, y, x)
    val zwyy get() = DVec4(z, w, y, y)
    val zwyz get() = DVec4(z, w, y, z)
    val zwyw get() = DVec4(z, w, y, w)
    val zwzx get() = DVec4(z, w, z, x)
    val zwzy get() = DVec4(z, w, z, y)
    val zwzz get() = DVec4(z, w, z, z)
    val zwzw get() = DVec4(z, w, z, w)
    val zwwx get() = DVec4(z, w, w, x)
    val zwwy get() = DVec4(z, w, w, y)
    val zwwz get() = DVec4(z, w, w, z)
    val zwww get() = DVec4(z, w, w, w)
    val wxxx get() = DVec4(w, x, x, x)
    val wxxy get() = DVec4(w, x, x, y)
    val wxxz get() = DVec4(w, x, x, z)
    val wxxw get() = DVec4(w, x, x, w)
    val wxyx get() = DVec4(w, x, y, x)
    val wxyy get() = DVec4(w, x, y, y)
    val wxyz get() = DVec4(w, x, y, z)
    val wxyw get() = DVec4(w, x, y, w)
    val wxzx get() = DVec4(w, x, z, x)
    val wxzy get() = DVec4(w, x, z, y)
    val wxzz get() = DVec4(w, x, z, z)
    val wxzw get() = DVec4(w, x, z, w)
    val wxwx get() = DVec4(w, x, w, x)
    val wxwy get() = DVec4(w, x, w, y)
    val wxwz get() = DVec4(w, x, w, z)
    val wxww get() = DVec4(w, x, w, w)
    val wyxx get() = DVec4(w, y, x, x)
    val wyxy get() = DVec4(w, y, x, y)
    val wyxz get() = DVec4(w, y, x, z)
    val wyxw get() = DVec4(w, y, x, w)
    val wyyx get() = DVec4(w, y, y, x)
    val wyyy get() = DVec4(w, y, y, y)
    val wyyz get() = DVec4(w, y, y, z)
    val wyyw get() = DVec4(w, y, y, w)
    val wyzx get() = DVec4(w, y, z, x)
    val wyzy get() = DVec4(w, y, z, y)
    val wyzz get() = DVec4(w, y, z, z)
    val wyzw get() = DVec4(w, y, z, w)
    val wywx get() = DVec4(w, y, w, x)
    val wywy get() = DVec4(w, y, w, y)
    val wywz get() = DVec4(w, y, w, z)
    val wyww get() = DVec4(w, y, w, w)
    val wzxx get() = DVec4(w, z, x, x)
    val wzxy get() = DVec4(w, z, x, y)
    val wzxz get() = DVec4(w, z, x, z)
    val wzxw get() = DVec4(w, z, x, w)
    val wzyx get() = DVec4(w, z, y, x)
    val wzyy get() = DVec4(w, z, y, y)
    val wzyz get() = DVec4(w, z, y, z)
    val wzyw get() = DVec4(w, z, y, w)
    val wzzx get() = DVec4(w, z, z, x)
    val wzzy get() = DVec4(w, z, z, y)
    val wzzz get() = DVec4(w, z, z, z)
    val wzzw get() = DVec4(w, z, z, w)
    val wzwx get() = DVec4(w, z, w, x)
    val wzwy get() = DVec4(w, z, w, y)
    val wzwz get() = DVec4(w, z, w, z)
    val wzww get() = DVec4(w, z, w, w)
    val wwxx get() = DVec4(w, w, x, x)
    val wwxy get() = DVec4(w, w, x, y)
    val wwxz get() = DVec4(w, w, x, z)
    val wwxw get() = DVec4(w, w, x, w)
    val wwyx get() = DVec4(w, w, y, x)
    val wwyy get() = DVec4(w, w, y, y)
    val wwyz get() = DVec4(w, w, y, z)
    val wwyw get() = DVec4(w, w, y, w)
    val wwzx get() = DVec4(w, w, z, x)
    val wwzy get() = DVec4(w, w, z, y)
    val wwzz get() = DVec4(w, w, z, z)
    val wwzw get() = DVec4(w, w, z, w)
    val wwwx get() = DVec4(w, w, w, x)
    val wwwy get() = DVec4(w, w, w, y)
    val wwwz get() = DVec4(w, w, w, z)
    val wwww get() = DVec4(w, w, w, w)

    override fun toString(): String {
        return ("DVec4(" + 
                "x=${"%.5f".format(Locale.ENGLISH, x)}, " + 
                "y=${"%.5f".format(Locale.ENGLISH, y)}, " + 
                "z=${"%.5f".format(Locale.ENGLISH, z)}, " + 
                "w=${"%.5f".format(Locale.ENGLISH, w)})")
    }

}

operator fun Double.plus(other: DVec4) = DVec4(this + other.x, this + other.y, this + other.z, this + other.w)
operator fun Double.minus(other: DVec4) = DVec4(this - other.x, this - other.y, this - other.z, this - other.w)
operator fun Double.times(other: DVec4) = DVec4(this * other.x, this * other.y, this * other.z, this * other.w)
operator fun Double.div(other: DVec4) = DVec4(this / other.x, this / other.y, this / other.z, this / other.w)
operator fun Double.rem(other: DVec4) = DVec4(this % other.x, this % other.y, this % other.z, this % other.w)

fun dvec4(value: Byte) = DVec4(value.toDouble())
fun dvec4(x: Byte, y: Byte, z: Byte, w: Byte) = DVec4(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
fun dvec4(value: Short) = DVec4(value.toDouble())
fun dvec4(x: Short, y: Short, z: Short, w: Short) = DVec4(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
fun dvec4(value: Int) = DVec4(value.toDouble())
fun dvec4(x: Int, y: Int, z: Int, w: Int) = DVec4(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
fun dvec4(value: Long) = DVec4(value.toDouble())
fun dvec4(x: Long, y: Long, z: Long, w: Long) = DVec4(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
fun dvec4(value: Float) = DVec4(value.toDouble())
fun dvec4(x: Float, y: Float, z: Float, w: Float) = DVec4(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())
fun dvec4(value: Double) = DVec4(value)
fun dvec4(x: Double, y: Double, z: Double, w: Double) = DVec4(x, y, z, w)
fun dvec4() = DVec4()
