package com.sloimay.smath.vectors

import java.util.*
import kotlin.math.*

data class Vec4(val x: Float, val y: Float, val z: Float, val w: Float) {

    companion object {
        fun splat(value: Byte) = Vec4(value, value, value, value)
        fun splat(value: Short) = Vec4(value, value, value, value)
        fun splat(value: Int) = Vec4(value, value, value, value)
        fun splat(value: Long) = Vec4(value, value, value, value)
        fun splat(value: Float) = Vec4(value, value, value, value)
        fun splat(value: Double) = Vec4(value, value, value, value)
        fun new(x: Byte, y: Byte, z: Byte, w: Byte) = Vec4(x, y, z, w)
        fun new(x: Short, y: Short, z: Short, w: Short) = Vec4(x, y, z, w)
        fun new(x: Int, y: Int, z: Int, w: Int) = Vec4(x, y, z, w)
        fun new(x: Long, y: Long, z: Long, w: Long) = Vec4(x, y, z, w)
        fun new(x: Float, y: Float, z: Float, w: Float) = Vec4(x, y, z, w)
        fun new(x: Double, y: Double, z: Double, w: Double) = Vec4(x, y, z, w)
        fun eye(index: Int, value: Float = 1.0f): Vec4 {
            require(index in 0 until 4) { 
                "Index out of bounds of the range [0; 4). (Got ${index})."
            }
            return Vec4(if (index == 0) value else 0.0f, if (index == 1) value else 0.0f, if (index == 2) value else 0.0f, if (index == 3) value else 0.0f)
        }

        fun fromArray(array: FloatArray): Vec4 {
            require(array.size == 4) { 
                "Inputted array isn't of the same dimensions as the vector we're trying to create. Expected 4, got ${array.size}."
            }
            return Vec4(array[0], array[1], array[2], array[3])
        }

        val X: Vec4 = Vec4(1.0f, 0.0f, 0.0f, 0.0f)
        val Y: Vec4 = Vec4(0.0f, 1.0f, 0.0f, 0.0f)
        val Z: Vec4 = Vec4(0.0f, 0.0f, 1.0f, 0.0f)
        val W: Vec4 = Vec4(0.0f, 0.0f, 0.0f, 1.0f)
        val ZERO: Vec4 = Vec4(0.0f)
        val ONE: Vec4 = Vec4(1.0f)
        val INF: Vec4 = Vec4(Float.POSITIVE_INFINITY)
        val NEG_INF: Vec4 = Vec4(Float.NEGATIVE_INFINITY)
        val MIN: Vec4 = Vec4(Float.MIN_VALUE)
        val MAX: Vec4 = Vec4(Float.MAX_VALUE)
    }

    constructor(value: Byte) : this(value.toFloat(), value.toFloat(), value.toFloat(), value.toFloat())
    constructor(x: Byte, y: Byte, z: Byte, w: Byte) : this(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
    constructor(value: Short) : this(value.toFloat(), value.toFloat(), value.toFloat(), value.toFloat())
    constructor(x: Short, y: Short, z: Short, w: Short) : this(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
    constructor(value: Int) : this(value.toFloat(), value.toFloat(), value.toFloat(), value.toFloat())
    constructor(x: Int, y: Int, z: Int, w: Int) : this(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
    constructor(value: Long) : this(value.toFloat(), value.toFloat(), value.toFloat(), value.toFloat())
    constructor(x: Long, y: Long, z: Long, w: Long) : this(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
    constructor(value: Float) : this(value, value, value, value)
    constructor(value: Double) : this(value.toFloat(), value.toFloat(), value.toFloat(), value.toFloat())
    constructor(x: Double, y: Double, z: Double, w: Double) : this(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
    constructor() : this(0.0f, 0.0f, 0.0f, 0.0f)
    constructor(lamb: (Int) -> Float) : this(lamb(0), lamb(1), lamb(2), lamb(3))

    operator fun plus(other: Vec4) = Vec4(x + other.x, y + other.y, z + other.z, w + other.w)
    operator fun plus(other: Float) = Vec4(x + other, y + other, z + other, w + other)
    operator fun minus(other: Vec4) = Vec4(x - other.x, y - other.y, z - other.z, w - other.w)
    operator fun minus(other: Float) = Vec4(x - other, y - other, z - other, w - other)
    operator fun times(other: Vec4) = Vec4(x * other.x, y * other.y, z * other.z, w * other.w)
    operator fun times(other: Float) = Vec4(x * other, y * other, z * other, w * other)
    operator fun div(other: Vec4) = Vec4(x / other.x, y / other.y, z / other.z, w / other.w)
    operator fun div(other: Float) = Vec4(x / other, y / other, z / other, w / other)
    operator fun rem(other: Vec4) = Vec4(x % other.x, y % other.y, z % other.z, w % other.w)
    operator fun rem(other: Float) = Vec4(x % other, y % other, z % other, w % other)
    operator fun unaryPlus() = this
    operator fun unaryMinus() = Vec4(-x, -y, -z, -w)
    operator fun get(idx: Byte): Float {
        require(idx in 0 until 4) { 
            "Vec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx.toInt()) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }
    operator fun get(idx: Short): Float {
        require(idx in 0 until 4) { 
            "Vec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx.toInt()) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }
    operator fun get(idx: Int): Float {
        require(idx in 0 until 4) { 
            "Vec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }
    operator fun get(idx: Long): Float {
        require(idx in 0 until 4) { 
            "Vec4 indexing failed. Index should be in the range of 0 to 3 (inclusive) but got ${idx}."
        }
        return when (idx.toInt()) { 0 -> x; 1 -> y; 2 -> z; else -> w }
    }

    fun toBVec4() = BVec4(x.toInt().toByte(), y.toInt().toByte(), z.toInt().toByte(), w.toInt().toByte())
    fun toSVec4() = SVec4(x.toInt().toShort(), y.toInt().toShort(), z.toInt().toShort(), w.toInt().toShort())
    fun toIVec4() = IVec4(x.toInt(), y.toInt(), z.toInt(), w.toInt())
    fun toLVec4() = LVec4(x.toLong(), y.toLong(), z.toLong(), w.toLong())
    fun toDVec4() = DVec4(x.toDouble(), y.toDouble(), z.toDouble(), w.toDouble())

    fun eq(other: Vec4) = x == other.x && y == other.y && z == other.z && w == other.w
    fun iter(): Iterator<Float> {
        return object : Iterator<Float> {
            private var idx = 0
            override fun hasNext() = idx < 4
            override fun next() = this@Vec4[idx++]
        }
    }
    fun seq() = iter().asSequence()
    fun abs() = Vec4(abs(x), abs(y), abs(z), abs(w))
    fun mod(value: Float) = Vec4(x.mod(value), y.mod(value), z.mod(value), w.mod(value))
    fun mod(other: Vec4) = Vec4(x.mod(other.x), y.mod(other.y), z.mod(other.z), w.mod(other.w))
    fun min(other: Vec4) = Vec4(min(x, other.x), min(y, other.y), min(z, other.z), min(w, other.w))
    fun min(other: Float) = Vec4(min(x, other), min(y, other), min(z, other), min(w, other))
    fun max(other: Vec4) = Vec4(max(x, other.x), max(y, other.y), max(z, other.z), max(w, other.w))
    fun max(other: Float) = Vec4(max(x, other), max(y, other), max(z, other), max(w, other))
    fun clamp(low: Vec4, high: Vec4) = Vec4(max(min(x, high.x), low.x), max(min(y, high.y), low.y), max(min(z, high.z), low.z), max(min(w, high.w), low.w))
    fun dot(other: Vec4) = x * other.x + y * other.y + z * other.z + w * other.w
    fun lenSq() = dot(this)
    fun len() = sqrt(lenSq())
    fun dist(other: Vec4) = (this - other).len()
    fun distSq(other: Vec4) = (this - other).lenSq()
    fun normalize() = this / len()
    fun dir() = this / len()
    fun elementSum() = ((x + y) + (z + w))
    fun eSum() = ((x + y) + (z + w))
    fun elementProd() = ((x * y) * (z * w))
    fun eProd() = ((x * y) * (z * w))
    fun minElement() = min(min(x, y), min(z, w))
    fun eMin() = min(min(x, y), min(z, w))
    fun maxElement() = max(max(x, y), max(z, w))
    fun eMax() = max(max(x, y), max(z, w))
    fun indexOfMin() = when (eMin()) { x -> 0; y -> 1; z -> 2; else -> 3 }
    fun indexOfMax() = when (eMax()) { x -> 0; y -> 1; z -> 2; else -> 3 }
    fun manhattan(other: Vec4) = (this - other).abs().eSum()
    fun toArray() = floatArrayOf(x, y, z, w)
    fun lerp(other: Vec4, t: Float) = this * (1.0f - t) + other * t
    fun floor() = Vec4(floor(x), floor(y), floor(z), floor(w))
    fun ceil() = Vec4(ceil(x), ceil(y), ceil(z), ceil(w))
    fun round() = Vec4(round(x), round(y), round(z), round(w))
    fun fract() = mod(1.0f)

    fun withElement(elementIdx: Int, value: Byte) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Short) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Int) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Long) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Float) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun withElement(elementIdx: Int, value: Double) = when (elementIdx) { 0 -> withX(value); 1 -> withY(value); 2 -> withZ(value); else -> withW(value) }
    fun perm(other: BVec2) = Vec2(this[other.x.toInt()], this[other.y.toInt()])
    fun perm(other: SVec2) = Vec2(this[other.x.toInt()], this[other.y.toInt()])
    fun perm(other: IVec2) = Vec2(this[other.x], this[other.y])
    fun perm(other: LVec2) = Vec2(this[other.x.toInt()], this[other.y.toInt()])
    fun perm(other: BVec3) = Vec3(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()])
    fun perm(other: SVec3) = Vec3(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()])
    fun perm(other: IVec3) = Vec3(this[other.x], this[other.y], this[other.z])
    fun perm(other: LVec3) = Vec3(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()])
    fun perm(other: BVec4) = Vec4(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()], this[other.w.toInt()])
    fun perm(other: SVec4) = Vec4(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()], this[other.w.toInt()])
    fun perm(other: IVec4) = Vec4(this[other.x], this[other.y], this[other.z], this[other.w])
    fun perm(other: LVec4) = Vec4(this[other.x.toInt()], this[other.y.toInt()], this[other.z.toInt()], this[other.w.toInt()])
    fun withX(value: Byte) = Vec4(value.toFloat(), y, z, w)
    fun withX(value: Short) = Vec4(value.toFloat(), y, z, w)
    fun withX(value: Int) = Vec4(value.toFloat(), y, z, w)
    fun withX(value: Long) = Vec4(value.toFloat(), y, z, w)
    fun withX(value: Float) = Vec4(value, y, z, w)
    fun withX(value: Double) = Vec4(value.toFloat(), y, z, w)
    fun withY(value: Byte) = Vec4(x, value.toFloat(), z, w)
    fun withY(value: Short) = Vec4(x, value.toFloat(), z, w)
    fun withY(value: Int) = Vec4(x, value.toFloat(), z, w)
    fun withY(value: Long) = Vec4(x, value.toFloat(), z, w)
    fun withY(value: Float) = Vec4(x, value, z, w)
    fun withY(value: Double) = Vec4(x, value.toFloat(), z, w)
    fun withZ(value: Byte) = Vec4(x, y, value.toFloat(), w)
    fun withZ(value: Short) = Vec4(x, y, value.toFloat(), w)
    fun withZ(value: Int) = Vec4(x, y, value.toFloat(), w)
    fun withZ(value: Long) = Vec4(x, y, value.toFloat(), w)
    fun withZ(value: Float) = Vec4(x, y, value, w)
    fun withZ(value: Double) = Vec4(x, y, value.toFloat(), w)
    fun withW(value: Byte) = Vec4(x, y, z, value.toFloat())
    fun withW(value: Short) = Vec4(x, y, z, value.toFloat())
    fun withW(value: Int) = Vec4(x, y, z, value.toFloat())
    fun withW(value: Long) = Vec4(x, y, z, value.toFloat())
    fun withW(value: Float) = Vec4(x, y, z, value)
    fun withW(value: Double) = Vec4(x, y, z, value.toFloat())

    val xx get() = Vec2(x, x)
    val xy get() = Vec2(x, y)
    val xz get() = Vec2(x, z)
    val xw get() = Vec2(x, w)
    val yx get() = Vec2(y, x)
    val yy get() = Vec2(y, y)
    val yz get() = Vec2(y, z)
    val yw get() = Vec2(y, w)
    val zx get() = Vec2(z, x)
    val zy get() = Vec2(z, y)
    val zz get() = Vec2(z, z)
    val zw get() = Vec2(z, w)
    val wx get() = Vec2(w, x)
    val wy get() = Vec2(w, y)
    val wz get() = Vec2(w, z)
    val ww get() = Vec2(w, w)
    val xxx get() = Vec3(x, x, x)
    val xxy get() = Vec3(x, x, y)
    val xxz get() = Vec3(x, x, z)
    val xxw get() = Vec3(x, x, w)
    val xyx get() = Vec3(x, y, x)
    val xyy get() = Vec3(x, y, y)
    val xyz get() = Vec3(x, y, z)
    val xyw get() = Vec3(x, y, w)
    val xzx get() = Vec3(x, z, x)
    val xzy get() = Vec3(x, z, y)
    val xzz get() = Vec3(x, z, z)
    val xzw get() = Vec3(x, z, w)
    val xwx get() = Vec3(x, w, x)
    val xwy get() = Vec3(x, w, y)
    val xwz get() = Vec3(x, w, z)
    val xww get() = Vec3(x, w, w)
    val yxx get() = Vec3(y, x, x)
    val yxy get() = Vec3(y, x, y)
    val yxz get() = Vec3(y, x, z)
    val yxw get() = Vec3(y, x, w)
    val yyx get() = Vec3(y, y, x)
    val yyy get() = Vec3(y, y, y)
    val yyz get() = Vec3(y, y, z)
    val yyw get() = Vec3(y, y, w)
    val yzx get() = Vec3(y, z, x)
    val yzy get() = Vec3(y, z, y)
    val yzz get() = Vec3(y, z, z)
    val yzw get() = Vec3(y, z, w)
    val ywx get() = Vec3(y, w, x)
    val ywy get() = Vec3(y, w, y)
    val ywz get() = Vec3(y, w, z)
    val yww get() = Vec3(y, w, w)
    val zxx get() = Vec3(z, x, x)
    val zxy get() = Vec3(z, x, y)
    val zxz get() = Vec3(z, x, z)
    val zxw get() = Vec3(z, x, w)
    val zyx get() = Vec3(z, y, x)
    val zyy get() = Vec3(z, y, y)
    val zyz get() = Vec3(z, y, z)
    val zyw get() = Vec3(z, y, w)
    val zzx get() = Vec3(z, z, x)
    val zzy get() = Vec3(z, z, y)
    val zzz get() = Vec3(z, z, z)
    val zzw get() = Vec3(z, z, w)
    val zwx get() = Vec3(z, w, x)
    val zwy get() = Vec3(z, w, y)
    val zwz get() = Vec3(z, w, z)
    val zww get() = Vec3(z, w, w)
    val wxx get() = Vec3(w, x, x)
    val wxy get() = Vec3(w, x, y)
    val wxz get() = Vec3(w, x, z)
    val wxw get() = Vec3(w, x, w)
    val wyx get() = Vec3(w, y, x)
    val wyy get() = Vec3(w, y, y)
    val wyz get() = Vec3(w, y, z)
    val wyw get() = Vec3(w, y, w)
    val wzx get() = Vec3(w, z, x)
    val wzy get() = Vec3(w, z, y)
    val wzz get() = Vec3(w, z, z)
    val wzw get() = Vec3(w, z, w)
    val wwx get() = Vec3(w, w, x)
    val wwy get() = Vec3(w, w, y)
    val wwz get() = Vec3(w, w, z)
    val www get() = Vec3(w, w, w)
    val xxxx get() = Vec4(x, x, x, x)
    val xxxy get() = Vec4(x, x, x, y)
    val xxxz get() = Vec4(x, x, x, z)
    val xxxw get() = Vec4(x, x, x, w)
    val xxyx get() = Vec4(x, x, y, x)
    val xxyy get() = Vec4(x, x, y, y)
    val xxyz get() = Vec4(x, x, y, z)
    val xxyw get() = Vec4(x, x, y, w)
    val xxzx get() = Vec4(x, x, z, x)
    val xxzy get() = Vec4(x, x, z, y)
    val xxzz get() = Vec4(x, x, z, z)
    val xxzw get() = Vec4(x, x, z, w)
    val xxwx get() = Vec4(x, x, w, x)
    val xxwy get() = Vec4(x, x, w, y)
    val xxwz get() = Vec4(x, x, w, z)
    val xxww get() = Vec4(x, x, w, w)
    val xyxx get() = Vec4(x, y, x, x)
    val xyxy get() = Vec4(x, y, x, y)
    val xyxz get() = Vec4(x, y, x, z)
    val xyxw get() = Vec4(x, y, x, w)
    val xyyx get() = Vec4(x, y, y, x)
    val xyyy get() = Vec4(x, y, y, y)
    val xyyz get() = Vec4(x, y, y, z)
    val xyyw get() = Vec4(x, y, y, w)
    val xyzx get() = Vec4(x, y, z, x)
    val xyzy get() = Vec4(x, y, z, y)
    val xyzz get() = Vec4(x, y, z, z)
    val xyzw get() = Vec4(x, y, z, w)
    val xywx get() = Vec4(x, y, w, x)
    val xywy get() = Vec4(x, y, w, y)
    val xywz get() = Vec4(x, y, w, z)
    val xyww get() = Vec4(x, y, w, w)
    val xzxx get() = Vec4(x, z, x, x)
    val xzxy get() = Vec4(x, z, x, y)
    val xzxz get() = Vec4(x, z, x, z)
    val xzxw get() = Vec4(x, z, x, w)
    val xzyx get() = Vec4(x, z, y, x)
    val xzyy get() = Vec4(x, z, y, y)
    val xzyz get() = Vec4(x, z, y, z)
    val xzyw get() = Vec4(x, z, y, w)
    val xzzx get() = Vec4(x, z, z, x)
    val xzzy get() = Vec4(x, z, z, y)
    val xzzz get() = Vec4(x, z, z, z)
    val xzzw get() = Vec4(x, z, z, w)
    val xzwx get() = Vec4(x, z, w, x)
    val xzwy get() = Vec4(x, z, w, y)
    val xzwz get() = Vec4(x, z, w, z)
    val xzww get() = Vec4(x, z, w, w)
    val xwxx get() = Vec4(x, w, x, x)
    val xwxy get() = Vec4(x, w, x, y)
    val xwxz get() = Vec4(x, w, x, z)
    val xwxw get() = Vec4(x, w, x, w)
    val xwyx get() = Vec4(x, w, y, x)
    val xwyy get() = Vec4(x, w, y, y)
    val xwyz get() = Vec4(x, w, y, z)
    val xwyw get() = Vec4(x, w, y, w)
    val xwzx get() = Vec4(x, w, z, x)
    val xwzy get() = Vec4(x, w, z, y)
    val xwzz get() = Vec4(x, w, z, z)
    val xwzw get() = Vec4(x, w, z, w)
    val xwwx get() = Vec4(x, w, w, x)
    val xwwy get() = Vec4(x, w, w, y)
    val xwwz get() = Vec4(x, w, w, z)
    val xwww get() = Vec4(x, w, w, w)
    val yxxx get() = Vec4(y, x, x, x)
    val yxxy get() = Vec4(y, x, x, y)
    val yxxz get() = Vec4(y, x, x, z)
    val yxxw get() = Vec4(y, x, x, w)
    val yxyx get() = Vec4(y, x, y, x)
    val yxyy get() = Vec4(y, x, y, y)
    val yxyz get() = Vec4(y, x, y, z)
    val yxyw get() = Vec4(y, x, y, w)
    val yxzx get() = Vec4(y, x, z, x)
    val yxzy get() = Vec4(y, x, z, y)
    val yxzz get() = Vec4(y, x, z, z)
    val yxzw get() = Vec4(y, x, z, w)
    val yxwx get() = Vec4(y, x, w, x)
    val yxwy get() = Vec4(y, x, w, y)
    val yxwz get() = Vec4(y, x, w, z)
    val yxww get() = Vec4(y, x, w, w)
    val yyxx get() = Vec4(y, y, x, x)
    val yyxy get() = Vec4(y, y, x, y)
    val yyxz get() = Vec4(y, y, x, z)
    val yyxw get() = Vec4(y, y, x, w)
    val yyyx get() = Vec4(y, y, y, x)
    val yyyy get() = Vec4(y, y, y, y)
    val yyyz get() = Vec4(y, y, y, z)
    val yyyw get() = Vec4(y, y, y, w)
    val yyzx get() = Vec4(y, y, z, x)
    val yyzy get() = Vec4(y, y, z, y)
    val yyzz get() = Vec4(y, y, z, z)
    val yyzw get() = Vec4(y, y, z, w)
    val yywx get() = Vec4(y, y, w, x)
    val yywy get() = Vec4(y, y, w, y)
    val yywz get() = Vec4(y, y, w, z)
    val yyww get() = Vec4(y, y, w, w)
    val yzxx get() = Vec4(y, z, x, x)
    val yzxy get() = Vec4(y, z, x, y)
    val yzxz get() = Vec4(y, z, x, z)
    val yzxw get() = Vec4(y, z, x, w)
    val yzyx get() = Vec4(y, z, y, x)
    val yzyy get() = Vec4(y, z, y, y)
    val yzyz get() = Vec4(y, z, y, z)
    val yzyw get() = Vec4(y, z, y, w)
    val yzzx get() = Vec4(y, z, z, x)
    val yzzy get() = Vec4(y, z, z, y)
    val yzzz get() = Vec4(y, z, z, z)
    val yzzw get() = Vec4(y, z, z, w)
    val yzwx get() = Vec4(y, z, w, x)
    val yzwy get() = Vec4(y, z, w, y)
    val yzwz get() = Vec4(y, z, w, z)
    val yzww get() = Vec4(y, z, w, w)
    val ywxx get() = Vec4(y, w, x, x)
    val ywxy get() = Vec4(y, w, x, y)
    val ywxz get() = Vec4(y, w, x, z)
    val ywxw get() = Vec4(y, w, x, w)
    val ywyx get() = Vec4(y, w, y, x)
    val ywyy get() = Vec4(y, w, y, y)
    val ywyz get() = Vec4(y, w, y, z)
    val ywyw get() = Vec4(y, w, y, w)
    val ywzx get() = Vec4(y, w, z, x)
    val ywzy get() = Vec4(y, w, z, y)
    val ywzz get() = Vec4(y, w, z, z)
    val ywzw get() = Vec4(y, w, z, w)
    val ywwx get() = Vec4(y, w, w, x)
    val ywwy get() = Vec4(y, w, w, y)
    val ywwz get() = Vec4(y, w, w, z)
    val ywww get() = Vec4(y, w, w, w)
    val zxxx get() = Vec4(z, x, x, x)
    val zxxy get() = Vec4(z, x, x, y)
    val zxxz get() = Vec4(z, x, x, z)
    val zxxw get() = Vec4(z, x, x, w)
    val zxyx get() = Vec4(z, x, y, x)
    val zxyy get() = Vec4(z, x, y, y)
    val zxyz get() = Vec4(z, x, y, z)
    val zxyw get() = Vec4(z, x, y, w)
    val zxzx get() = Vec4(z, x, z, x)
    val zxzy get() = Vec4(z, x, z, y)
    val zxzz get() = Vec4(z, x, z, z)
    val zxzw get() = Vec4(z, x, z, w)
    val zxwx get() = Vec4(z, x, w, x)
    val zxwy get() = Vec4(z, x, w, y)
    val zxwz get() = Vec4(z, x, w, z)
    val zxww get() = Vec4(z, x, w, w)
    val zyxx get() = Vec4(z, y, x, x)
    val zyxy get() = Vec4(z, y, x, y)
    val zyxz get() = Vec4(z, y, x, z)
    val zyxw get() = Vec4(z, y, x, w)
    val zyyx get() = Vec4(z, y, y, x)
    val zyyy get() = Vec4(z, y, y, y)
    val zyyz get() = Vec4(z, y, y, z)
    val zyyw get() = Vec4(z, y, y, w)
    val zyzx get() = Vec4(z, y, z, x)
    val zyzy get() = Vec4(z, y, z, y)
    val zyzz get() = Vec4(z, y, z, z)
    val zyzw get() = Vec4(z, y, z, w)
    val zywx get() = Vec4(z, y, w, x)
    val zywy get() = Vec4(z, y, w, y)
    val zywz get() = Vec4(z, y, w, z)
    val zyww get() = Vec4(z, y, w, w)
    val zzxx get() = Vec4(z, z, x, x)
    val zzxy get() = Vec4(z, z, x, y)
    val zzxz get() = Vec4(z, z, x, z)
    val zzxw get() = Vec4(z, z, x, w)
    val zzyx get() = Vec4(z, z, y, x)
    val zzyy get() = Vec4(z, z, y, y)
    val zzyz get() = Vec4(z, z, y, z)
    val zzyw get() = Vec4(z, z, y, w)
    val zzzx get() = Vec4(z, z, z, x)
    val zzzy get() = Vec4(z, z, z, y)
    val zzzz get() = Vec4(z, z, z, z)
    val zzzw get() = Vec4(z, z, z, w)
    val zzwx get() = Vec4(z, z, w, x)
    val zzwy get() = Vec4(z, z, w, y)
    val zzwz get() = Vec4(z, z, w, z)
    val zzww get() = Vec4(z, z, w, w)
    val zwxx get() = Vec4(z, w, x, x)
    val zwxy get() = Vec4(z, w, x, y)
    val zwxz get() = Vec4(z, w, x, z)
    val zwxw get() = Vec4(z, w, x, w)
    val zwyx get() = Vec4(z, w, y, x)
    val zwyy get() = Vec4(z, w, y, y)
    val zwyz get() = Vec4(z, w, y, z)
    val zwyw get() = Vec4(z, w, y, w)
    val zwzx get() = Vec4(z, w, z, x)
    val zwzy get() = Vec4(z, w, z, y)
    val zwzz get() = Vec4(z, w, z, z)
    val zwzw get() = Vec4(z, w, z, w)
    val zwwx get() = Vec4(z, w, w, x)
    val zwwy get() = Vec4(z, w, w, y)
    val zwwz get() = Vec4(z, w, w, z)
    val zwww get() = Vec4(z, w, w, w)
    val wxxx get() = Vec4(w, x, x, x)
    val wxxy get() = Vec4(w, x, x, y)
    val wxxz get() = Vec4(w, x, x, z)
    val wxxw get() = Vec4(w, x, x, w)
    val wxyx get() = Vec4(w, x, y, x)
    val wxyy get() = Vec4(w, x, y, y)
    val wxyz get() = Vec4(w, x, y, z)
    val wxyw get() = Vec4(w, x, y, w)
    val wxzx get() = Vec4(w, x, z, x)
    val wxzy get() = Vec4(w, x, z, y)
    val wxzz get() = Vec4(w, x, z, z)
    val wxzw get() = Vec4(w, x, z, w)
    val wxwx get() = Vec4(w, x, w, x)
    val wxwy get() = Vec4(w, x, w, y)
    val wxwz get() = Vec4(w, x, w, z)
    val wxww get() = Vec4(w, x, w, w)
    val wyxx get() = Vec4(w, y, x, x)
    val wyxy get() = Vec4(w, y, x, y)
    val wyxz get() = Vec4(w, y, x, z)
    val wyxw get() = Vec4(w, y, x, w)
    val wyyx get() = Vec4(w, y, y, x)
    val wyyy get() = Vec4(w, y, y, y)
    val wyyz get() = Vec4(w, y, y, z)
    val wyyw get() = Vec4(w, y, y, w)
    val wyzx get() = Vec4(w, y, z, x)
    val wyzy get() = Vec4(w, y, z, y)
    val wyzz get() = Vec4(w, y, z, z)
    val wyzw get() = Vec4(w, y, z, w)
    val wywx get() = Vec4(w, y, w, x)
    val wywy get() = Vec4(w, y, w, y)
    val wywz get() = Vec4(w, y, w, z)
    val wyww get() = Vec4(w, y, w, w)
    val wzxx get() = Vec4(w, z, x, x)
    val wzxy get() = Vec4(w, z, x, y)
    val wzxz get() = Vec4(w, z, x, z)
    val wzxw get() = Vec4(w, z, x, w)
    val wzyx get() = Vec4(w, z, y, x)
    val wzyy get() = Vec4(w, z, y, y)
    val wzyz get() = Vec4(w, z, y, z)
    val wzyw get() = Vec4(w, z, y, w)
    val wzzx get() = Vec4(w, z, z, x)
    val wzzy get() = Vec4(w, z, z, y)
    val wzzz get() = Vec4(w, z, z, z)
    val wzzw get() = Vec4(w, z, z, w)
    val wzwx get() = Vec4(w, z, w, x)
    val wzwy get() = Vec4(w, z, w, y)
    val wzwz get() = Vec4(w, z, w, z)
    val wzww get() = Vec4(w, z, w, w)
    val wwxx get() = Vec4(w, w, x, x)
    val wwxy get() = Vec4(w, w, x, y)
    val wwxz get() = Vec4(w, w, x, z)
    val wwxw get() = Vec4(w, w, x, w)
    val wwyx get() = Vec4(w, w, y, x)
    val wwyy get() = Vec4(w, w, y, y)
    val wwyz get() = Vec4(w, w, y, z)
    val wwyw get() = Vec4(w, w, y, w)
    val wwzx get() = Vec4(w, w, z, x)
    val wwzy get() = Vec4(w, w, z, y)
    val wwzz get() = Vec4(w, w, z, z)
    val wwzw get() = Vec4(w, w, z, w)
    val wwwx get() = Vec4(w, w, w, x)
    val wwwy get() = Vec4(w, w, w, y)
    val wwwz get() = Vec4(w, w, w, z)
    val wwww get() = Vec4(w, w, w, w)

    override fun toString(): String {
        return ("Vec4(" + 
                "x=${"%.5f".format(Locale.ENGLISH, x)}, " + 
                "y=${"%.5f".format(Locale.ENGLISH, y)}, " + 
                "z=${"%.5f".format(Locale.ENGLISH, z)}, " + 
                "w=${"%.5f".format(Locale.ENGLISH, w)})")
    }

}

operator fun Float.plus(other: Vec4) = Vec4(this + other.x, this + other.y, this + other.z, this + other.w)
operator fun Float.minus(other: Vec4) = Vec4(this - other.x, this - other.y, this - other.z, this - other.w)
operator fun Float.times(other: Vec4) = Vec4(this * other.x, this * other.y, this * other.z, this * other.w)
operator fun Float.div(other: Vec4) = Vec4(this / other.x, this / other.y, this / other.z, this / other.w)
operator fun Float.rem(other: Vec4) = Vec4(this % other.x, this % other.y, this % other.z, this % other.w)

fun vec4(value: Byte) = Vec4(value.toFloat())
fun vec4(x: Byte, y: Byte, z: Byte, w: Byte) = Vec4(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
fun vec4(value: Short) = Vec4(value.toFloat())
fun vec4(x: Short, y: Short, z: Short, w: Short) = Vec4(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
fun vec4(value: Int) = Vec4(value.toFloat())
fun vec4(x: Int, y: Int, z: Int, w: Int) = Vec4(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
fun vec4(value: Long) = Vec4(value.toFloat())
fun vec4(x: Long, y: Long, z: Long, w: Long) = Vec4(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
fun vec4(value: Float) = Vec4(value)
fun vec4(x: Float, y: Float, z: Float, w: Float) = Vec4(x, y, z, w)
fun vec4(value: Double) = Vec4(value.toFloat())
fun vec4(x: Double, y: Double, z: Double, w: Double) = Vec4(x.toFloat(), y.toFloat(), z.toFloat(), w.toFloat())
fun vec4() = Vec4()
