package me.sloimay.smath.vectors.swizzles

import me.sloimay.smath.vectors.IVec2
import me.sloimay.smath.vectors.IVec3


val IVec3.xx get() = IVec2.new(x, x)
val IVec3.xy get() = IVec2.new(x, y)
val IVec3.xz get() = IVec2.new(x, z)
val IVec3.yx get() = IVec2.new(y, x)
val IVec3.yy get() = IVec2.new(y, y)
val IVec3.yz get() = IVec2.new(y, z)
val IVec3.zx get() = IVec2.new(z, x)
val IVec3.zy get() = IVec2.new(z, y)
val IVec3.zz get() = IVec2.new(z, z)
val IVec3.xxx get() = IVec3.new(x, x, x)
val IVec3.xxy get() = IVec3.new(x, x, y)
val IVec3.xxz get() = IVec3.new(x, x, z)
val IVec3.xyx get() = IVec3.new(x, y, x)
val IVec3.xyy get() = IVec3.new(x, y, y)
val IVec3.xyz get() = IVec3.new(x, y, z)
val IVec3.xzx get() = IVec3.new(x, z, x)
val IVec3.xzy get() = IVec3.new(x, z, y)
val IVec3.xzz get() = IVec3.new(x, z, z)
val IVec3.yxx get() = IVec3.new(y, x, x)
val IVec3.yxy get() = IVec3.new(y, x, y)
val IVec3.yxz get() = IVec3.new(y, x, z)
val IVec3.yyx get() = IVec3.new(y, y, x)
val IVec3.yyy get() = IVec3.new(y, y, y)
val IVec3.yyz get() = IVec3.new(y, y, z)
val IVec3.yzx get() = IVec3.new(y, z, x)
val IVec3.yzy get() = IVec3.new(y, z, y)
val IVec3.yzz get() = IVec3.new(y, z, z)
val IVec3.zxx get() = IVec3.new(z, x, x)
val IVec3.zxy get() = IVec3.new(z, x, y)
val IVec3.zxz get() = IVec3.new(z, x, z)
val IVec3.zyx get() = IVec3.new(z, y, x)
val IVec3.zyy get() = IVec3.new(z, y, y)
val IVec3.zyz get() = IVec3.new(z, y, z)
val IVec3.zzx get() = IVec3.new(z, z, x)
val IVec3.zzy get() = IVec3.new(z, z, y)
val IVec3.zzz get() = IVec3.new(z, z, z)